/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_VoltMon_cfg.h"

static const char* CMockString_VoltMon_CfgGet_pcfg = "VoltMon_CfgGet_pcfg";

typedef struct _CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  const VoltMon_cfg_s* ReturnVal;
  int CallOrder;

} CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE;

static struct mock_VoltMon_cfgInstance
{
  char VoltMon_CfgGet_pcfg_IgnoreBool;
  const VoltMon_cfg_s* VoltMon_CfgGet_pcfg_FinalReturn;
  char VoltMon_CfgGet_pcfg_CallbackBool;
  CMOCK_VoltMon_CfgGet_pcfg_CALLBACK VoltMon_CfgGet_pcfg_CallbackFunctionPointer;
  int VoltMon_CfgGet_pcfg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE VoltMon_CfgGet_pcfg_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_VoltMon_cfg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.VoltMon_CfgGet_pcfg_CallInstance;
  if (Mock.VoltMon_CfgGet_pcfg_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_VoltMon_CfgGet_pcfg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_VoltMon_cfg_Init(void)
{
  mock_VoltMon_cfg_Destroy();
}

void mock_VoltMon_cfg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

const VoltMon_cfg_s* VoltMon_CfgGet_pcfg(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_VoltMon_CfgGet_pcfg);
  cmock_call_instance = (CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.VoltMon_CfgGet_pcfg_CallInstance);
  Mock.VoltMon_CfgGet_pcfg_CallInstance = CMock_Guts_MemNext(Mock.VoltMon_CfgGet_pcfg_CallInstance);
  if (Mock.VoltMon_CfgGet_pcfg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.VoltMon_CfgGet_pcfg_FinalReturn;
    Mock.VoltMon_CfgGet_pcfg_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.VoltMon_CfgGet_pcfg_CallbackBool &&
      Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer != NULL)
  {
    const VoltMon_cfg_s* cmock_cb_ret = Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer(Mock.VoltMon_CfgGet_pcfg_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer(Mock.VoltMon_CfgGet_pcfg_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void VoltMon_CfgGet_pcfg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const VoltMon_cfg_s* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE));
  CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.VoltMon_CfgGet_pcfg_CallInstance = CMock_Guts_MemChain(Mock.VoltMon_CfgGet_pcfg_CallInstance, cmock_guts_index);
  Mock.VoltMon_CfgGet_pcfg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.VoltMon_CfgGet_pcfg_IgnoreBool = (char)1;
}

void VoltMon_CfgGet_pcfg_CMockStopIgnore(void)
{
  if(Mock.VoltMon_CfgGet_pcfg_IgnoreBool)
    Mock.VoltMon_CfgGet_pcfg_CallInstance = CMock_Guts_MemNext(Mock.VoltMon_CfgGet_pcfg_CallInstance);
  Mock.VoltMon_CfgGet_pcfg_IgnoreBool = (char)0;
}

void VoltMon_CfgGet_pcfg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const VoltMon_cfg_s* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE));
  CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_VoltMon_CfgGet_pcfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.VoltMon_CfgGet_pcfg_CallInstance = CMock_Guts_MemChain(Mock.VoltMon_CfgGet_pcfg_CallInstance, cmock_guts_index);
  Mock.VoltMon_CfgGet_pcfg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void VoltMon_CfgGet_pcfg_AddCallback(CMOCK_VoltMon_CfgGet_pcfg_CALLBACK Callback)
{
  Mock.VoltMon_CfgGet_pcfg_IgnoreBool = (char)0;
  Mock.VoltMon_CfgGet_pcfg_CallbackBool = (char)1;
  Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer = Callback;
}

void VoltMon_CfgGet_pcfg_Stub(CMOCK_VoltMon_CfgGet_pcfg_CALLBACK Callback)
{
  Mock.VoltMon_CfgGet_pcfg_IgnoreBool = (char)0;
  Mock.VoltMon_CfgGet_pcfg_CallbackBool = (char)0;
  Mock.VoltMon_CfgGet_pcfg_CallbackFunctionPointer = Callback;
}

