/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_VOLTMON_PRIV_H
#define _MOCK_VOLTMON_PRIV_H

#include "unity.h"
#include "VoltMon_priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_VoltMon_priv_Init(void);
void mock_VoltMon_priv_Destroy(void);
void mock_VoltMon_priv_Verify(void);




#define ComputeVoltage_u16_Ignore() TEST_FAIL_MESSAGE("ComputeVoltage_u16 requires _IgnoreAndReturn");
#define ComputeVoltage_u16_IgnoreAndReturn(cmock_retval) ComputeVoltage_u16_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ComputeVoltage_u16_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define ComputeVoltage_u16_StopIgnore() ComputeVoltage_u16_CMockStopIgnore()
void ComputeVoltage_u16_CMockStopIgnore(void);
#define ComputeVoltage_u16_ExpectAnyArgs() TEST_FAIL_MESSAGE("ComputeVoltage_u16 requires _ExpectAnyArgsAndReturn");
#define ComputeVoltage_u16_ExpectAnyArgsAndReturn(cmock_retval) ComputeVoltage_u16_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ComputeVoltage_u16_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define ComputeVoltage_u16_Expect(rawAdc_u16, cfg_pcs) TEST_FAIL_MESSAGE("ComputeVoltage_u16 requires _ExpectAndReturn");
#define ComputeVoltage_u16_ExpectAndReturn(rawAdc_u16, cfg_pcs, cmock_retval) ComputeVoltage_u16_CMockExpectAndReturn(__LINE__, rawAdc_u16, cfg_pcs, cmock_retval)
void ComputeVoltage_u16_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_ComputeVoltage_u16_CALLBACK)(uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, int cmock_num_calls);
void ComputeVoltage_u16_AddCallback(CMOCK_ComputeVoltage_u16_CALLBACK Callback);
void ComputeVoltage_u16_Stub(CMOCK_ComputeVoltage_u16_CALLBACK Callback);
#define ComputeVoltage_u16_StubWithCallback ComputeVoltage_u16_Stub
#define ComputeVoltage_u16_ExpectWithArray(rawAdc_u16, cfg_pcs, cfg_pcs_Depth) TEST_FAIL_MESSAGE("ComputeVoltage_u16 requires _ExpectWithArrayAndReturn");
#define ComputeVoltage_u16_ExpectWithArrayAndReturn(rawAdc_u16, cfg_pcs, cfg_pcs_Depth, cmock_retval) ComputeVoltage_u16_CMockExpectWithArrayAndReturn(__LINE__, rawAdc_u16, cfg_pcs, (cfg_pcs_Depth), cmock_retval)
void ComputeVoltage_u16_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth, uint16_t cmock_to_return);
#define ComputeVoltage_u16_IgnoreArg_rawAdc_u16() ComputeVoltage_u16_CMockIgnoreArg_rawAdc_u16(__LINE__)
void ComputeVoltage_u16_CMockIgnoreArg_rawAdc_u16(UNITY_LINE_TYPE cmock_line);
#define ComputeVoltage_u16_IgnoreArg_cfg_pcs() ComputeVoltage_u16_CMockIgnoreArg_cfg_pcs(__LINE__)
void ComputeVoltage_u16_CMockIgnoreArg_cfg_pcs(UNITY_LINE_TYPE cmock_line);
#define CheckThresholds_u8_Ignore() TEST_FAIL_MESSAGE("CheckThresholds_u8 requires _IgnoreAndReturn");
#define CheckThresholds_u8_IgnoreAndReturn(cmock_retval) CheckThresholds_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CheckThresholds_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define CheckThresholds_u8_StopIgnore() CheckThresholds_u8_CMockStopIgnore()
void CheckThresholds_u8_CMockStopIgnore(void);
#define CheckThresholds_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("CheckThresholds_u8 requires _ExpectAnyArgsAndReturn");
#define CheckThresholds_u8_ExpectAnyArgsAndReturn(cmock_retval) CheckThresholds_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void CheckThresholds_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define CheckThresholds_u8_Expect(voltage_mV_u16, cfg_pcs, uvActive_pb, ovActive_pb) TEST_FAIL_MESSAGE("CheckThresholds_u8 requires _ExpectAndReturn");
#define CheckThresholds_u8_ExpectAndReturn(voltage_mV_u16, cfg_pcs, uvActive_pb, ovActive_pb, cmock_retval) CheckThresholds_u8_CMockExpectAndReturn(__LINE__, voltage_mV_u16, cfg_pcs, uvActive_pb, ovActive_pb, cmock_retval)
void CheckThresholds_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, _Bool* uvActive_pb, _Bool* ovActive_pb, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_CheckThresholds_u8_CALLBACK)(uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, _Bool* uvActive_pb, _Bool* ovActive_pb, int cmock_num_calls);
void CheckThresholds_u8_AddCallback(CMOCK_CheckThresholds_u8_CALLBACK Callback);
void CheckThresholds_u8_Stub(CMOCK_CheckThresholds_u8_CALLBACK Callback);
#define CheckThresholds_u8_StubWithCallback CheckThresholds_u8_Stub
#define CheckThresholds_u8_ExpectWithArray(voltage_mV_u16, cfg_pcs, cfg_pcs_Depth, uvActive_pb, uvActive_pb_Depth, ovActive_pb, ovActive_pb_Depth) TEST_FAIL_MESSAGE("CheckThresholds_u8 requires _ExpectWithArrayAndReturn");
#define CheckThresholds_u8_ExpectWithArrayAndReturn(voltage_mV_u16, cfg_pcs, cfg_pcs_Depth, uvActive_pb, uvActive_pb_Depth, ovActive_pb, ovActive_pb_Depth, cmock_retval) CheckThresholds_u8_CMockExpectWithArrayAndReturn(__LINE__, voltage_mV_u16, cfg_pcs, (cfg_pcs_Depth), uvActive_pb, (uvActive_pb_Depth), ovActive_pb, (ovActive_pb_Depth), cmock_retval)
void CheckThresholds_u8_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth, _Bool* uvActive_pb, int uvActive_pb_Depth, _Bool* ovActive_pb, int ovActive_pb_Depth, uint8_t cmock_to_return);
#define CheckThresholds_u8_ReturnThruPtr_uvActive_pb(uvActive_pb) CheckThresholds_u8_CMockReturnMemThruPtr_uvActive_pb(__LINE__, uvActive_pb, sizeof(_Bool))
#define CheckThresholds_u8_ReturnArrayThruPtr_uvActive_pb(uvActive_pb, cmock_len) CheckThresholds_u8_CMockReturnMemThruPtr_uvActive_pb(__LINE__, uvActive_pb, (cmock_len * sizeof(*uvActive_pb)))
#define CheckThresholds_u8_ReturnMemThruPtr_uvActive_pb(uvActive_pb, cmock_size) CheckThresholds_u8_CMockReturnMemThruPtr_uvActive_pb(__LINE__, uvActive_pb, (cmock_size))
void CheckThresholds_u8_CMockReturnMemThruPtr_uvActive_pb(UNITY_LINE_TYPE cmock_line, _Bool const* uvActive_pb, size_t cmock_size);
#define CheckThresholds_u8_ReturnThruPtr_ovActive_pb(ovActive_pb) CheckThresholds_u8_CMockReturnMemThruPtr_ovActive_pb(__LINE__, ovActive_pb, sizeof(_Bool))
#define CheckThresholds_u8_ReturnArrayThruPtr_ovActive_pb(ovActive_pb, cmock_len) CheckThresholds_u8_CMockReturnMemThruPtr_ovActive_pb(__LINE__, ovActive_pb, (cmock_len * sizeof(*ovActive_pb)))
#define CheckThresholds_u8_ReturnMemThruPtr_ovActive_pb(ovActive_pb, cmock_size) CheckThresholds_u8_CMockReturnMemThruPtr_ovActive_pb(__LINE__, ovActive_pb, (cmock_size))
void CheckThresholds_u8_CMockReturnMemThruPtr_ovActive_pb(UNITY_LINE_TYPE cmock_line, _Bool const* ovActive_pb, size_t cmock_size);
#define CheckThresholds_u8_IgnoreArg_voltage_mV_u16() CheckThresholds_u8_CMockIgnoreArg_voltage_mV_u16(__LINE__)
void CheckThresholds_u8_CMockIgnoreArg_voltage_mV_u16(UNITY_LINE_TYPE cmock_line);
#define CheckThresholds_u8_IgnoreArg_cfg_pcs() CheckThresholds_u8_CMockIgnoreArg_cfg_pcs(__LINE__)
void CheckThresholds_u8_CMockIgnoreArg_cfg_pcs(UNITY_LINE_TYPE cmock_line);
#define CheckThresholds_u8_IgnoreArg_uvActive_pb() CheckThresholds_u8_CMockIgnoreArg_uvActive_pb(__LINE__)
void CheckThresholds_u8_CMockIgnoreArg_uvActive_pb(UNITY_LINE_TYPE cmock_line);
#define CheckThresholds_u8_IgnoreArg_ovActive_pb() CheckThresholds_u8_CMockIgnoreArg_ovActive_pb(__LINE__)
void CheckThresholds_u8_CMockIgnoreArg_ovActive_pb(UNITY_LINE_TYPE cmock_line);
#define UpdateStatusFlags_v_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("UpdateStatusFlags_v requires _Ignore (not AndReturn)");
#define UpdateStatusFlags_v_Ignore() UpdateStatusFlags_v_CMockIgnore()
void UpdateStatusFlags_v_CMockIgnore(void);
#define UpdateStatusFlags_v_StopIgnore() UpdateStatusFlags_v_CMockStopIgnore()
void UpdateStatusFlags_v_CMockStopIgnore(void);
#define UpdateStatusFlags_v_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("UpdateStatusFlags_v requires _ExpectAnyArgs (not AndReturn)");
#define UpdateStatusFlags_v_ExpectAnyArgs() UpdateStatusFlags_v_CMockExpectAnyArgs(__LINE__)
void UpdateStatusFlags_v_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define UpdateStatusFlags_v_ExpectAndReturn(uvActive_b, ovActive_b, errSticky_b, cmock_retval) TEST_FAIL_MESSAGE("UpdateStatusFlags_v requires _Expect (not AndReturn)");
#define UpdateStatusFlags_v_Expect(uvActive_b, ovActive_b, errSticky_b) UpdateStatusFlags_v_CMockExpect(__LINE__, uvActive_b, ovActive_b, errSticky_b)
void UpdateStatusFlags_v_CMockExpect(UNITY_LINE_TYPE cmock_line, _Bool uvActive_b, _Bool ovActive_b, _Bool errSticky_b);
typedef void (* CMOCK_UpdateStatusFlags_v_CALLBACK)(_Bool uvActive_b, _Bool ovActive_b, _Bool errSticky_b, int cmock_num_calls);
void UpdateStatusFlags_v_AddCallback(CMOCK_UpdateStatusFlags_v_CALLBACK Callback);
void UpdateStatusFlags_v_Stub(CMOCK_UpdateStatusFlags_v_CALLBACK Callback);
#define UpdateStatusFlags_v_StubWithCallback UpdateStatusFlags_v_Stub
#define UpdateStatusFlags_v_IgnoreArg_uvActive_b() UpdateStatusFlags_v_CMockIgnoreArg_uvActive_b(__LINE__)
void UpdateStatusFlags_v_CMockIgnoreArg_uvActive_b(UNITY_LINE_TYPE cmock_line);
#define UpdateStatusFlags_v_IgnoreArg_ovActive_b() UpdateStatusFlags_v_CMockIgnoreArg_ovActive_b(__LINE__)
void UpdateStatusFlags_v_CMockIgnoreArg_ovActive_b(UNITY_LINE_TYPE cmock_line);
#define UpdateStatusFlags_v_IgnoreArg_errSticky_b() UpdateStatusFlags_v_CMockIgnoreArg_errSticky_b(__LINE__)
void UpdateStatusFlags_v_CMockIgnoreArg_errSticky_b(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
