/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "unity.h"
#include "VoltMon_Init_u8.h"
#include "mock_VoltMon_cfg.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void testVariablesAsset(uint32_t expStatusFlg_u32, VoltMon_mode_e expMode_e, uint16_t expLastRawAdc_u16, uint16_t expLastVoltage_mV_u16,
                                                                                                                                        _Bool
                                                                                                                                             expUvActive_b,
                                                                                                                                                            _Bool
                                                                                                                                                                 expOvActive_b);
extern void testVariableReset(uint32_t statusFlg_u32, VoltMon_mode_e mode_e, uint16_t lastRawAdc_u16, uint16_t lastVoltage_mV_u16,
                                                                                                                           _Bool
                                                                                                                                uvActive_b,
                                                                                                                                            _Bool
                                                                                                                                                 ovActive_b);
extern void test_VoltMon_Init_u8_should_return_1_and_set_ERR_when_cfg_is_NULL(void);
extern void test_VoltMon_Init_u8_should_return_1_and_set_ERR_when_rawMax_is_0(void);
extern void test_VoltMon_Init_u8_should_return_0_set_INIT_and_clear_flags_when_cfg_is_valid(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_VoltMon_cfg_Init();
}
static void CMock_Verify(void)
{
  mock_VoltMon_cfg_Verify();
}
static void CMock_Destroy(void)
{
  mock_VoltMon_cfg_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_VoltMon_Init_u8.c");
  run_test(testVariablesAsset, "testVariablesAsset", 16);
  run_test(testVariableReset, "testVariableReset", 25);
  run_test(test_VoltMon_Init_u8_should_return_1_and_set_ERR_when_cfg_is_NULL, "test_VoltMon_Init_u8_should_return_1_and_set_ERR_when_cfg_is_NULL", 49);
  run_test(test_VoltMon_Init_u8_should_return_1_and_set_ERR_when_rawMax_is_0, "test_VoltMon_Init_u8_should_return_1_and_set_ERR_when_rawMax_is_0", 68);
  run_test(test_VoltMon_Init_u8_should_return_0_set_INIT_and_clear_flags_when_cfg_is_valid, "test_VoltMon_Init_u8_should_return_0_set_INIT_and_clear_flags_when_cfg_is_valid", 96);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
