/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "VoltMon.h"
#include "VoltMon_UpdateAdc_u8.h"
#include "VoltMon_cfg.h"
#include "VoltMon_priv.h"
#include "unity.h"
#include "mock_VoltMon_cfg.h"
#include "mock_VoltMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_VoltMon_UpdateAdc_u8_returns_invalid_param_for_rawAdc_above_max(void);
extern void test_VoltMon_UpdateAdc_u8_returns_not_init_when_mode_is_idle(void);
extern void test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_under_uv_threshold(void);
extern void test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_under_ov_threshold(void);
extern void test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_with_no_thresholds_active(void);
extern void test_VoltMon_UpdateAdc_u8_returns_busy_when_mode_diag(void);
extern void test_VoltMon_UpdateAdc_u8_voltage_exactly_at_uv_threshold_sets_uv_active(void);
extern void test_VoltMon_UpdateAdc_u8_voltage_just_below_uv_threshold_clears_uv_active(void);
extern void test_VoltMon_UpdateAdc_u8_voltage_just_above_uv_threshold_sets_uv_active(void);
extern void test_VoltMon_UpdateAdc_u8_voltage_exactly_at_ov_threshold_sets_ov_active(void);
extern void test_VoltMon_UpdateAdc_u8_voltage_just_below_ov_threshold_clears_ov_active(void);
extern void test_VoltMon_UpdateAdc_u8_voltage_just_above_ov_threshold_sets_ov_active(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_VoltMon_cfg_Init();
  mock_VoltMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_VoltMon_cfg_Verify();
  mock_VoltMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_VoltMon_cfg_Destroy();
  mock_VoltMon_priv_Destroy();
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_VoltMon_UpdateAdc_u8.c");
  run_test(test_VoltMon_UpdateAdc_u8_returns_invalid_param_for_rawAdc_above_max, "test_VoltMon_UpdateAdc_u8_returns_invalid_param_for_rawAdc_above_max", 11);
  run_test(test_VoltMon_UpdateAdc_u8_returns_not_init_when_mode_is_idle, "test_VoltMon_UpdateAdc_u8_returns_not_init_when_mode_is_idle", 18);
  run_test(test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_under_uv_threshold, "test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_under_uv_threshold", 25);
  run_test(test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_under_ov_threshold, "test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_under_ov_threshold", 53);
  run_test(test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_with_no_thresholds_active, "test_VoltMon_UpdateAdc_u8_updates_voltage_and_status_with_no_thresholds_active", 73);
  run_test(test_VoltMon_UpdateAdc_u8_returns_busy_when_mode_diag, "test_VoltMon_UpdateAdc_u8_returns_busy_when_mode_diag", 93);
  run_test(test_VoltMon_UpdateAdc_u8_voltage_exactly_at_uv_threshold_sets_uv_active, "test_VoltMon_UpdateAdc_u8_voltage_exactly_at_uv_threshold_sets_uv_active", 100);
  run_test(test_VoltMon_UpdateAdc_u8_voltage_just_below_uv_threshold_clears_uv_active, "test_VoltMon_UpdateAdc_u8_voltage_just_below_uv_threshold_clears_uv_active", 117);
  run_test(test_VoltMon_UpdateAdc_u8_voltage_just_above_uv_threshold_sets_uv_active, "test_VoltMon_UpdateAdc_u8_voltage_just_above_uv_threshold_sets_uv_active", 135);
  run_test(test_VoltMon_UpdateAdc_u8_voltage_exactly_at_ov_threshold_sets_ov_active, "test_VoltMon_UpdateAdc_u8_voltage_exactly_at_ov_threshold_sets_ov_active", 153);
  run_test(test_VoltMon_UpdateAdc_u8_voltage_just_below_ov_threshold_clears_ov_active, "test_VoltMon_UpdateAdc_u8_voltage_just_below_ov_threshold_clears_ov_active", 171);
  run_test(test_VoltMon_UpdateAdc_u8_voltage_just_above_ov_threshold_sets_ov_active, "test_VoltMon_UpdateAdc_u8_voltage_just_above_ov_threshold_sets_ov_active", 189);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
