/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "VoltMon.h"
#include "VoltMon_UpdateAdc_u8.h"
#include "VoltMon_cfg.h"
#include "VoltMon_priv.h"
#include "unity.h"
#include "mock_VoltMon_cfg.h"
#include "mock_VoltMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_flag_if_not_initialized(void);
extern void test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_and_inval_flags_if_cfg_is_null(void);
extern void test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_and_inval_flags_if_rawAdc_greater_than_rawMax(void);
extern void test_VoltMon_UpdateAdc_u8_updates_raw_and_voltage_and_clears_inval_flag_when_input_valid(void);
extern void test_VoltMon_UpdateAdc_u8_accepts_rawAdc_equal_to_rawMax(void);
extern void test_VoltMon_UpdateAdc_u8_accepts_rawAdc_just_below_rawMax(void);
extern void test_VoltMon_UpdateAdc_u8_rejects_rawAdc_just_above_rawMax(void);
extern void test_VoltMon_UpdateAdc_u8_rejects_when_config_pointer_is_null_even_if_initialized(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_VoltMon_cfg_Init();
  mock_VoltMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_VoltMon_cfg_Verify();
  mock_VoltMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_VoltMon_cfg_Destroy();
  mock_VoltMon_priv_Destroy();
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_VoltMon_UpdateAdc_u8.c");
  run_test(test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_flag_if_not_initialized, "test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_flag_if_not_initialized", 22);
  run_test(test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_and_inval_flags_if_cfg_is_null, "test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_and_inval_flags_if_cfg_is_null", 32);
  run_test(test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_and_inval_flags_if_rawAdc_greater_than_rawMax, "test_VoltMon_UpdateAdc_u8_returns_error_and_sets_err_and_inval_flags_if_rawAdc_greater_than_rawMax", 42);
  run_test(test_VoltMon_UpdateAdc_u8_updates_raw_and_voltage_and_clears_inval_flag_when_input_valid, "test_VoltMon_UpdateAdc_u8_updates_raw_and_voltage_and_clears_inval_flag_when_input_valid", 54);
  run_test(test_VoltMon_UpdateAdc_u8_accepts_rawAdc_equal_to_rawMax, "test_VoltMon_UpdateAdc_u8_accepts_rawAdc_equal_to_rawMax", 69);
  run_test(test_VoltMon_UpdateAdc_u8_accepts_rawAdc_just_below_rawMax, "test_VoltMon_UpdateAdc_u8_accepts_rawAdc_just_below_rawMax", 83);
  run_test(test_VoltMon_UpdateAdc_u8_rejects_rawAdc_just_above_rawMax, "test_VoltMon_UpdateAdc_u8_rejects_rawAdc_just_above_rawMax", 97);
  run_test(test_VoltMon_UpdateAdc_u8_rejects_when_config_pointer_is_null_even_if_initialized, "test_VoltMon_UpdateAdc_u8_rejects_when_config_pointer_is_null_even_if_initialized", 109);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
