/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_VOLTMON_CFG_H
#define _MOCK_VOLTMON_CFG_H

#include "unity.h"
#include "VoltMon_cfg.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_VoltMon_cfg_Init(void);
void mock_VoltMon_cfg_Destroy(void);
void mock_VoltMon_cfg_Verify(void);




#define VoltMon_CfgGet_pcfg_Ignore() TEST_FAIL_MESSAGE("VoltMon_CfgGet_pcfg requires _IgnoreAndReturn");
#define VoltMon_CfgGet_pcfg_IgnoreAndReturn(cmock_retval) VoltMon_CfgGet_pcfg_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void VoltMon_CfgGet_pcfg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const VoltMon_cfg_s* cmock_to_return);
#define VoltMon_CfgGet_pcfg_StopIgnore() VoltMon_CfgGet_pcfg_CMockStopIgnore()
void VoltMon_CfgGet_pcfg_CMockStopIgnore(void);
#define VoltMon_CfgGet_pcfg_Expect() TEST_FAIL_MESSAGE("VoltMon_CfgGet_pcfg requires _ExpectAndReturn");
#define VoltMon_CfgGet_pcfg_ExpectAndReturn(cmock_retval) VoltMon_CfgGet_pcfg_CMockExpectAndReturn(__LINE__, cmock_retval)
void VoltMon_CfgGet_pcfg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const VoltMon_cfg_s* cmock_to_return);
typedef const VoltMon_cfg_s* (* CMOCK_VoltMon_CfgGet_pcfg_CALLBACK)(int cmock_num_calls);
void VoltMon_CfgGet_pcfg_AddCallback(CMOCK_VoltMon_CfgGet_pcfg_CALLBACK Callback);
void VoltMon_CfgGet_pcfg_Stub(CMOCK_VoltMon_CfgGet_pcfg_CALLBACK Callback);
#define VoltMon_CfgGet_pcfg_StubWithCallback VoltMon_CfgGet_pcfg_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
