/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_VoltMon_priv.h"

static const char* CMockString_CheckThresholds_u8 = "CheckThresholds_u8";
static const char* CMockString_ComputeVoltage_u16 = "ComputeVoltage_u16";
static const char* CMockString_UpdateStatusFlags_v = "UpdateStatusFlags_v";
static const char* CMockString_cfg_pcs = "cfg_pcs";
static const char* CMockString_errSticky_b = "errSticky_b";
static const char* CMockString_ovActive_b = "ovActive_b";
static const char* CMockString_ovActive_pb = "ovActive_pb";
static const char* CMockString_rawAdc_u16 = "rawAdc_u16";
static const char* CMockString_uvActive_b = "uvActive_b";
static const char* CMockString_uvActive_pb = "uvActive_pb";
static const char* CMockString_voltage_mV_u16 = "voltage_mV_u16";

typedef struct _CMOCK_ComputeVoltage_u16_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t ReturnVal;
  int CallOrder;
  uint16_t Expected_rawAdc_u16;
  const VoltMon_cfg_s* Expected_cfg_pcs;
  int Expected_cfg_pcs_Depth;
  char IgnoreArg_rawAdc_u16;
  char IgnoreArg_cfg_pcs;

} CMOCK_ComputeVoltage_u16_CALL_INSTANCE;

typedef struct _CMOCK_CheckThresholds_u8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  uint16_t Expected_voltage_mV_u16;
  const VoltMon_cfg_s* Expected_cfg_pcs;
  _Bool* Expected_uvActive_pb;
  _Bool* Expected_ovActive_pb;
  int Expected_cfg_pcs_Depth;
  int Expected_uvActive_pb_Depth;
  int Expected_ovActive_pb_Depth;
  char ReturnThruPtr_uvActive_pb_Used;
  _Bool const* ReturnThruPtr_uvActive_pb_Val;
  size_t ReturnThruPtr_uvActive_pb_Size;
  char ReturnThruPtr_ovActive_pb_Used;
  _Bool const* ReturnThruPtr_ovActive_pb_Val;
  size_t ReturnThruPtr_ovActive_pb_Size;
  char IgnoreArg_voltage_mV_u16;
  char IgnoreArg_cfg_pcs;
  char IgnoreArg_uvActive_pb;
  char IgnoreArg_ovActive_pb;

} CMOCK_CheckThresholds_u8_CALL_INSTANCE;

typedef struct _CMOCK_UpdateStatusFlags_v_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  _Bool Expected_uvActive_b;
  _Bool Expected_ovActive_b;
  _Bool Expected_errSticky_b;
  char IgnoreArg_uvActive_b;
  char IgnoreArg_ovActive_b;
  char IgnoreArg_errSticky_b;

} CMOCK_UpdateStatusFlags_v_CALL_INSTANCE;

static struct mock_VoltMon_privInstance
{
  char ComputeVoltage_u16_IgnoreBool;
  uint16_t ComputeVoltage_u16_FinalReturn;
  char ComputeVoltage_u16_CallbackBool;
  CMOCK_ComputeVoltage_u16_CALLBACK ComputeVoltage_u16_CallbackFunctionPointer;
  int ComputeVoltage_u16_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ComputeVoltage_u16_CallInstance;
  char CheckThresholds_u8_IgnoreBool;
  uint8_t CheckThresholds_u8_FinalReturn;
  char CheckThresholds_u8_CallbackBool;
  CMOCK_CheckThresholds_u8_CALLBACK CheckThresholds_u8_CallbackFunctionPointer;
  int CheckThresholds_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CheckThresholds_u8_CallInstance;
  char UpdateStatusFlags_v_IgnoreBool;
  char UpdateStatusFlags_v_CallbackBool;
  CMOCK_UpdateStatusFlags_v_CALLBACK UpdateStatusFlags_v_CallbackFunctionPointer;
  int UpdateStatusFlags_v_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UpdateStatusFlags_v_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_VoltMon_priv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.ComputeVoltage_u16_CallInstance;
  if (Mock.ComputeVoltage_u16_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ComputeVoltage_u16);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ComputeVoltage_u16_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.CheckThresholds_u8_CallInstance;
  if (Mock.CheckThresholds_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CheckThresholds_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CheckThresholds_u8_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UpdateStatusFlags_v_CallInstance;
  if (Mock.UpdateStatusFlags_v_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UpdateStatusFlags_v);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UpdateStatusFlags_v_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_VoltMon_priv_Init(void)
{
  mock_VoltMon_priv_Destroy();
}

void mock_VoltMon_priv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

uint16_t ComputeVoltage_u16(uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ComputeVoltage_u16);
  cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ComputeVoltage_u16_CallInstance);
  Mock.ComputeVoltage_u16_CallInstance = CMock_Guts_MemNext(Mock.ComputeVoltage_u16_CallInstance);
  if (Mock.ComputeVoltage_u16_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ComputeVoltage_u16_FinalReturn;
    Mock.ComputeVoltage_u16_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ComputeVoltage_u16_CallbackBool &&
      Mock.ComputeVoltage_u16_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.ComputeVoltage_u16_CallbackFunctionPointer(rawAdc_u16, cfg_pcs, Mock.ComputeVoltage_u16_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_rawAdc_u16)
  {
    UNITY_SET_DETAILS(CMockString_ComputeVoltage_u16,CMockString_rawAdc_u16);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_rawAdc_u16, rawAdc_u16, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cfg_pcs)
  {
    UNITY_SET_DETAILS(CMockString_ComputeVoltage_u16,CMockString_cfg_pcs);
    if (cmock_call_instance->Expected_cfg_pcs == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg_pcs, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg_pcs), (void*)(cfg_pcs), sizeof(const VoltMon_cfg_s), cmock_call_instance->Expected_cfg_pcs_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.ComputeVoltage_u16_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ComputeVoltage_u16_CallbackFunctionPointer(rawAdc_u16, cfg_pcs, Mock.ComputeVoltage_u16_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ComputeVoltage_u16(CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance, uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth);
void CMockExpectParameters_ComputeVoltage_u16(CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance, uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth)
{
  cmock_call_instance->Expected_rawAdc_u16 = rawAdc_u16;
  cmock_call_instance->IgnoreArg_rawAdc_u16 = 0;
  cmock_call_instance->Expected_cfg_pcs = cfg_pcs;
  cmock_call_instance->Expected_cfg_pcs_Depth = cfg_pcs_Depth;
  cmock_call_instance->IgnoreArg_cfg_pcs = 0;
}

void ComputeVoltage_u16_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ComputeVoltage_u16_CALL_INSTANCE));
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ComputeVoltage_u16_CallInstance = CMock_Guts_MemChain(Mock.ComputeVoltage_u16_CallInstance, cmock_guts_index);
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ComputeVoltage_u16_IgnoreBool = (char)1;
}

void ComputeVoltage_u16_CMockStopIgnore(void)
{
  if(Mock.ComputeVoltage_u16_IgnoreBool)
    Mock.ComputeVoltage_u16_CallInstance = CMock_Guts_MemNext(Mock.ComputeVoltage_u16_CallInstance);
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
}

void ComputeVoltage_u16_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ComputeVoltage_u16_CALL_INSTANCE));
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ComputeVoltage_u16_CallInstance = CMock_Guts_MemChain(Mock.ComputeVoltage_u16_CallInstance, cmock_guts_index);
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ComputeVoltage_u16_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ComputeVoltage_u16_CALL_INSTANCE));
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ComputeVoltage_u16_CallInstance = CMock_Guts_MemChain(Mock.ComputeVoltage_u16_CallInstance, cmock_guts_index);
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ComputeVoltage_u16(cmock_call_instance, rawAdc_u16, cfg_pcs, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ComputeVoltage_u16_AddCallback(CMOCK_ComputeVoltage_u16_CALLBACK Callback)
{
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
  Mock.ComputeVoltage_u16_CallbackBool = (char)1;
  Mock.ComputeVoltage_u16_CallbackFunctionPointer = Callback;
}

void ComputeVoltage_u16_Stub(CMOCK_ComputeVoltage_u16_CALLBACK Callback)
{
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
  Mock.ComputeVoltage_u16_CallbackBool = (char)0;
  Mock.ComputeVoltage_u16_CallbackFunctionPointer = Callback;
}

void ComputeVoltage_u16_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t rawAdc_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ComputeVoltage_u16_CALL_INSTANCE));
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ComputeVoltage_u16_CallInstance = CMock_Guts_MemChain(Mock.ComputeVoltage_u16_CallInstance, cmock_guts_index);
  Mock.ComputeVoltage_u16_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ComputeVoltage_u16(cmock_call_instance, rawAdc_u16, cfg_pcs, cfg_pcs_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ComputeVoltage_u16_CMockIgnoreArg_rawAdc_u16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ComputeVoltage_u16_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_rawAdc_u16 = 1;
}

void ComputeVoltage_u16_CMockIgnoreArg_cfg_pcs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ComputeVoltage_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_ComputeVoltage_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ComputeVoltage_u16_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg_pcs = 1;
}

uint8_t CheckThresholds_u8(uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, _Bool* uvActive_pb, _Bool* ovActive_pb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CheckThresholds_u8);
  cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CheckThresholds_u8_CallInstance);
  Mock.CheckThresholds_u8_CallInstance = CMock_Guts_MemNext(Mock.CheckThresholds_u8_CallInstance);
  if (Mock.CheckThresholds_u8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CheckThresholds_u8_FinalReturn;
    Mock.CheckThresholds_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CheckThresholds_u8_CallbackBool &&
      Mock.CheckThresholds_u8_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.CheckThresholds_u8_CallbackFunctionPointer(voltage_mV_u16, cfg_pcs, uvActive_pb, ovActive_pb, Mock.CheckThresholds_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_voltage_mV_u16)
  {
    UNITY_SET_DETAILS(CMockString_CheckThresholds_u8,CMockString_voltage_mV_u16);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_voltage_mV_u16, voltage_mV_u16, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cfg_pcs)
  {
    UNITY_SET_DETAILS(CMockString_CheckThresholds_u8,CMockString_cfg_pcs);
    if (cmock_call_instance->Expected_cfg_pcs == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg_pcs, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg_pcs), (void*)(cfg_pcs), sizeof(const VoltMon_cfg_s), cmock_call_instance->Expected_cfg_pcs_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_uvActive_pb)
  {
    UNITY_SET_DETAILS(CMockString_CheckThresholds_u8,CMockString_uvActive_pb);
    if (cmock_call_instance->Expected_uvActive_pb == NULL)
      { UNITY_TEST_ASSERT_NULL(uvActive_pb, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_uvActive_pb), (void*)(uvActive_pb), sizeof(_Bool), cmock_call_instance->Expected_uvActive_pb_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_ovActive_pb)
  {
    UNITY_SET_DETAILS(CMockString_CheckThresholds_u8,CMockString_ovActive_pb);
    if (cmock_call_instance->Expected_ovActive_pb == NULL)
      { UNITY_TEST_ASSERT_NULL(ovActive_pb, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_ovActive_pb), (void*)(ovActive_pb), sizeof(_Bool), cmock_call_instance->Expected_ovActive_pb_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.CheckThresholds_u8_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.CheckThresholds_u8_CallbackFunctionPointer(voltage_mV_u16, cfg_pcs, uvActive_pb, ovActive_pb, Mock.CheckThresholds_u8_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_uvActive_pb_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(uvActive_pb, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)uvActive_pb, (const void*)cmock_call_instance->ReturnThruPtr_uvActive_pb_Val,
      cmock_call_instance->ReturnThruPtr_uvActive_pb_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_ovActive_pb_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(ovActive_pb, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)ovActive_pb, (const void*)cmock_call_instance->ReturnThruPtr_ovActive_pb_Val,
      cmock_call_instance->ReturnThruPtr_ovActive_pb_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_CheckThresholds_u8(CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance, uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth, _Bool* uvActive_pb, int uvActive_pb_Depth, _Bool* ovActive_pb, int ovActive_pb_Depth);
void CMockExpectParameters_CheckThresholds_u8(CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance, uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth, _Bool* uvActive_pb, int uvActive_pb_Depth, _Bool* ovActive_pb, int ovActive_pb_Depth)
{
  cmock_call_instance->Expected_voltage_mV_u16 = voltage_mV_u16;
  cmock_call_instance->IgnoreArg_voltage_mV_u16 = 0;
  cmock_call_instance->Expected_cfg_pcs = cfg_pcs;
  cmock_call_instance->Expected_cfg_pcs_Depth = cfg_pcs_Depth;
  cmock_call_instance->IgnoreArg_cfg_pcs = 0;
  cmock_call_instance->Expected_uvActive_pb = uvActive_pb;
  cmock_call_instance->Expected_uvActive_pb_Depth = uvActive_pb_Depth;
  cmock_call_instance->IgnoreArg_uvActive_pb = 0;
  cmock_call_instance->ReturnThruPtr_uvActive_pb_Used = 0;
  cmock_call_instance->Expected_ovActive_pb = ovActive_pb;
  cmock_call_instance->Expected_ovActive_pb_Depth = ovActive_pb_Depth;
  cmock_call_instance->IgnoreArg_ovActive_pb = 0;
  cmock_call_instance->ReturnThruPtr_ovActive_pb_Used = 0;
}

void CheckThresholds_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CheckThresholds_u8_CALL_INSTANCE));
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CheckThresholds_u8_CallInstance = CMock_Guts_MemChain(Mock.CheckThresholds_u8_CallInstance, cmock_guts_index);
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CheckThresholds_u8_IgnoreBool = (char)1;
}

void CheckThresholds_u8_CMockStopIgnore(void)
{
  if(Mock.CheckThresholds_u8_IgnoreBool)
    Mock.CheckThresholds_u8_CallInstance = CMock_Guts_MemNext(Mock.CheckThresholds_u8_CallInstance);
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
}

void CheckThresholds_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CheckThresholds_u8_CALL_INSTANCE));
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CheckThresholds_u8_CallInstance = CMock_Guts_MemChain(Mock.CheckThresholds_u8_CallInstance, cmock_guts_index);
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void CheckThresholds_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, _Bool* uvActive_pb, _Bool* ovActive_pb, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CheckThresholds_u8_CALL_INSTANCE));
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CheckThresholds_u8_CallInstance = CMock_Guts_MemChain(Mock.CheckThresholds_u8_CallInstance, cmock_guts_index);
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_CheckThresholds_u8(cmock_call_instance, voltage_mV_u16, cfg_pcs, 1, uvActive_pb, 1, ovActive_pb, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CheckThresholds_u8_AddCallback(CMOCK_CheckThresholds_u8_CALLBACK Callback)
{
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
  Mock.CheckThresholds_u8_CallbackBool = (char)1;
  Mock.CheckThresholds_u8_CallbackFunctionPointer = Callback;
}

void CheckThresholds_u8_Stub(CMOCK_CheckThresholds_u8_CALLBACK Callback)
{
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
  Mock.CheckThresholds_u8_CallbackBool = (char)0;
  Mock.CheckThresholds_u8_CallbackFunctionPointer = Callback;
}

void CheckThresholds_u8_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t voltage_mV_u16, const VoltMon_cfg_s* cfg_pcs, int cfg_pcs_Depth, _Bool* uvActive_pb, int uvActive_pb_Depth, _Bool* ovActive_pb, int ovActive_pb_Depth, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CheckThresholds_u8_CALL_INSTANCE));
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CheckThresholds_u8_CallInstance = CMock_Guts_MemChain(Mock.CheckThresholds_u8_CallInstance, cmock_guts_index);
  Mock.CheckThresholds_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_CheckThresholds_u8(cmock_call_instance, voltage_mV_u16, cfg_pcs, cfg_pcs_Depth, uvActive_pb, uvActive_pb_Depth, ovActive_pb, ovActive_pb_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CheckThresholds_u8_CMockReturnMemThruPtr_uvActive_pb(UNITY_LINE_TYPE cmock_line, _Bool const* uvActive_pb, size_t cmock_size)
{
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.CheckThresholds_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_uvActive_pb_Used = 1;
  cmock_call_instance->ReturnThruPtr_uvActive_pb_Val = uvActive_pb;
  cmock_call_instance->ReturnThruPtr_uvActive_pb_Size = cmock_size;
}

void CheckThresholds_u8_CMockReturnMemThruPtr_ovActive_pb(UNITY_LINE_TYPE cmock_line, _Bool const* ovActive_pb, size_t cmock_size)
{
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.CheckThresholds_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_ovActive_pb_Used = 1;
  cmock_call_instance->ReturnThruPtr_ovActive_pb_Val = ovActive_pb;
  cmock_call_instance->ReturnThruPtr_ovActive_pb_Size = cmock_size;
}

void CheckThresholds_u8_CMockIgnoreArg_voltage_mV_u16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.CheckThresholds_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_voltage_mV_u16 = 1;
}

void CheckThresholds_u8_CMockIgnoreArg_cfg_pcs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.CheckThresholds_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg_pcs = 1;
}

void CheckThresholds_u8_CMockIgnoreArg_uvActive_pb(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.CheckThresholds_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_uvActive_pb = 1;
}

void CheckThresholds_u8_CMockIgnoreArg_ovActive_pb(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_CheckThresholds_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_CheckThresholds_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.CheckThresholds_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ovActive_pb = 1;
}

void UpdateStatusFlags_v(_Bool uvActive_b, _Bool ovActive_b, _Bool errSticky_b)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UpdateStatusFlags_v);
  cmock_call_instance = (CMOCK_UpdateStatusFlags_v_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UpdateStatusFlags_v_CallInstance);
  Mock.UpdateStatusFlags_v_CallInstance = CMock_Guts_MemNext(Mock.UpdateStatusFlags_v_CallInstance);
  if (Mock.UpdateStatusFlags_v_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UpdateStatusFlags_v_CallbackBool &&
      Mock.UpdateStatusFlags_v_CallbackFunctionPointer != NULL)
  {
    Mock.UpdateStatusFlags_v_CallbackFunctionPointer(uvActive_b, ovActive_b, errSticky_b, Mock.UpdateStatusFlags_v_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_uvActive_b)
  {
    UNITY_SET_DETAILS(CMockString_UpdateStatusFlags_v,CMockString_uvActive_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_uvActive_b), (void*)(&uvActive_b), sizeof(_Bool), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_ovActive_b)
  {
    UNITY_SET_DETAILS(CMockString_UpdateStatusFlags_v,CMockString_ovActive_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ovActive_b), (void*)(&ovActive_b), sizeof(_Bool), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_errSticky_b)
  {
    UNITY_SET_DETAILS(CMockString_UpdateStatusFlags_v,CMockString_errSticky_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_errSticky_b), (void*)(&errSticky_b), sizeof(_Bool), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.UpdateStatusFlags_v_CallbackFunctionPointer != NULL)
  {
    Mock.UpdateStatusFlags_v_CallbackFunctionPointer(uvActive_b, ovActive_b, errSticky_b, Mock.UpdateStatusFlags_v_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UpdateStatusFlags_v(CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance, _Bool uvActive_b, _Bool ovActive_b, _Bool errSticky_b);
void CMockExpectParameters_UpdateStatusFlags_v(CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance, _Bool uvActive_b, _Bool ovActive_b, _Bool errSticky_b)
{
  memcpy((void*)(&cmock_call_instance->Expected_uvActive_b), (void*)(&uvActive_b),
         sizeof(_Bool[sizeof(uvActive_b) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_uvActive_b = 0;
  memcpy((void*)(&cmock_call_instance->Expected_ovActive_b), (void*)(&ovActive_b),
         sizeof(_Bool[sizeof(ovActive_b) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_ovActive_b = 0;
  memcpy((void*)(&cmock_call_instance->Expected_errSticky_b), (void*)(&errSticky_b),
         sizeof(_Bool[sizeof(errSticky_b) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_errSticky_b = 0;
}

void UpdateStatusFlags_v_CMockIgnore(void)
{
  Mock.UpdateStatusFlags_v_IgnoreBool = (char)1;
}

void UpdateStatusFlags_v_CMockStopIgnore(void)
{
  Mock.UpdateStatusFlags_v_IgnoreBool = (char)0;
}

void UpdateStatusFlags_v_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UpdateStatusFlags_v_CALL_INSTANCE));
  CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance = (CMOCK_UpdateStatusFlags_v_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UpdateStatusFlags_v_CallInstance = CMock_Guts_MemChain(Mock.UpdateStatusFlags_v_CallInstance, cmock_guts_index);
  Mock.UpdateStatusFlags_v_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void UpdateStatusFlags_v_CMockExpect(UNITY_LINE_TYPE cmock_line, _Bool uvActive_b, _Bool ovActive_b, _Bool errSticky_b)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UpdateStatusFlags_v_CALL_INSTANCE));
  CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance = (CMOCK_UpdateStatusFlags_v_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UpdateStatusFlags_v_CallInstance = CMock_Guts_MemChain(Mock.UpdateStatusFlags_v_CallInstance, cmock_guts_index);
  Mock.UpdateStatusFlags_v_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_UpdateStatusFlags_v(cmock_call_instance, uvActive_b, ovActive_b, errSticky_b);
}

void UpdateStatusFlags_v_AddCallback(CMOCK_UpdateStatusFlags_v_CALLBACK Callback)
{
  Mock.UpdateStatusFlags_v_IgnoreBool = (char)0;
  Mock.UpdateStatusFlags_v_CallbackBool = (char)1;
  Mock.UpdateStatusFlags_v_CallbackFunctionPointer = Callback;
}

void UpdateStatusFlags_v_Stub(CMOCK_UpdateStatusFlags_v_CALLBACK Callback)
{
  Mock.UpdateStatusFlags_v_IgnoreBool = (char)0;
  Mock.UpdateStatusFlags_v_CallbackBool = (char)0;
  Mock.UpdateStatusFlags_v_CallbackFunctionPointer = Callback;
}

void UpdateStatusFlags_v_CMockIgnoreArg_uvActive_b(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance = (CMOCK_UpdateStatusFlags_v_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UpdateStatusFlags_v_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_uvActive_b = 1;
}

void UpdateStatusFlags_v_CMockIgnoreArg_ovActive_b(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance = (CMOCK_UpdateStatusFlags_v_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UpdateStatusFlags_v_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ovActive_b = 1;
}

void UpdateStatusFlags_v_CMockIgnoreArg_errSticky_b(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UpdateStatusFlags_v_CALL_INSTANCE* cmock_call_instance = (CMOCK_UpdateStatusFlags_v_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UpdateStatusFlags_v_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_errSticky_b = 1;
}

